export enum SocketKeys {
  NEW_MEMBER = 'NEW_MEMBER',
  LAVE = 'LAVE_MEMBER',
  UPDATE_MEMBER = 'UPDATE_MEMBER',
  KICK_MEMBER = 'KICK_MEMBER',
  CREATE_MESSAGE = 'CREATE_MESSAGE',
  UPDATE_MESSAGE = 'UPDATE_MESSAGE',
  DELETE_MESSAGE = 'DELETE_MESSAGE',
  UPDATE_MEMBER_STATUS = 'UPDATE_MEMBER_STATUS',

  STREAM_GET_CURRENT_PLAYING = 'GET_CURRENT_PLAYING',
  STREAM_CB_CURRENT_PLAYING = 'CB_CURRENT_PLAYING',
  STREAM_FETCH_CURRENT_PLAYING = 'FETCH_CURRENT_PLAYING',
  STREAM_PLAY = 'STREAM_PLAY',
  STREAM_TOGGLE_PLAY = 'TOGGLE_PLAY',
  STREAM_SEEK = 'STREAM_SEEK',
  FETCH_ONLINE_MEMBERS = 'FETCH_ONLINE_MEMBERS',
}
